### ISSUE TITLE
Can't launch SDK 3.0.10 on MacOS Sierra

### ISSUE THREAD

**Issue by songproducer** [jMonkeyEngine/sdk#100]
I tried opening in Terminal as well but no output. I also have JDK 1.8 installed.

**Comment by grizeldi** [comment]
Step 1: dont use 3.0 but 3.1, because 3.0 is not being maintained anymore.

**Comment by MeFisto94** [comment]
Exactly that.
And for 3.1 we'd need more information about it since when you launch it in terminal you should have some output

**Comment by muellermartin** [comment]
I do have exactly the same issue. I'd suggest a notice (README/release notes/website) to spare some time and bandwidth.

**Comment by MeFisto94** [comment]
And 3.1 fixed it for you? (Because I don't actually think so).

We'd need some debugging output, the best would be some `ant run` after having built the sdk (`./build_engine.sh` and then `./gradlew buildSdk`).

I can atleast verify that both 3.0 and 3.1 work fine on 10.9.5 and don't see an actual reason why they don't work on sierra, though.

**Comment by muellermartin** [comment]
@MeFisto94 jMonkeyEngine SDK 3.1.0-beta2-b001-SNAPSHOT seems to start on macOS 10.12.2 in contrast to the current release tag. I didn't test anything besides that.

I might include some debugging output of the 3.0.0 version if I find the time.

**Comment by muellermartin** [comment]
This is the log file for version 3.1.0 (built with `./build_engine.sh` and `./gradlew buildSdk` and creating an unmodified BasicGame projec and running it once): https://gist.github.com/muellermartin/5f6104a6d2851b34fda24085bdcbdc6f

Currently I'm not able to build the SDK version 3.0.0 `stable` tag at 283bc294 (using `./gradlew buildSdk` - there is no shell script like in the newer version) because of this error:

```
Warning: getReleaseInfo() found an errorneous tag: "stable". Syntax Error: The Tags Main Version didn't consist of two/three parts
Full Version: 3.1-HEAD-1624
POM Version: 3.1.0-HEAD-SNAPSHOT
NBM Revision: 1624
NBM UC Suffix: HEAD-nightly/3.1/plugins
Download http://jcenter.bintray.com/org/jmonkeyengine/jme3-effects/3.1.0-beta1/jme3-effects-3.1.0-beta1.pom
Download http://jcenter.bintray.com/org/jmonkeyengine/jme3-blender/3.1.0-beta1/jme3-blender-3.1.0-beta1.pom
Download http://jcenter.bintray.com/org/jmonkeyengine/jme3-jogg/3.1.0-beta1/jme3-jogg-3.1.0-beta1.pom
Download http://jcenter.bintray.com/org/jmonkeyengine/jme3-networking/3.1.0-beta1/jme3-networking-3.1.0-beta1.pom
Download http://jcenter.bintray.com/org/jmonkeyengine/jme3-niftygui/3.1.0-beta1/jme3-niftygui-3.1.0-beta1.pom
Download http://jcenter.bintray.com/org/jmonkeyengine/jme3-plugins/3.1.0-beta1/jme3-plugins-3.1.0-beta1.pom

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/martin/Projects/jMonkeyEngine-sdk/build.gradle' line: 130

* What went wrong:
A problem occurred evaluating root project 'jMonkeyEngine-sdk'.
> Could not resolve all dependencies for configuration ':corelibs'.
   > Could not find org.jmonkeyengine:jme3-jbullet:3.1.0-beta1.
     Searched in the following locations:
         http://jcenter.bintray.com/org/jmonkeyengine/jme3-jbullet/3.1.0-beta1/jme3-jbullet-3.1.0-beta1.pom
         http://jcenter.bintray.com/org/jmonkeyengine/jme3-jbullet/3.1.0-beta1/jme3-jbullet-3.1.0-beta1.jar
         http://updates.jmonkeyengine.org/maven/org/jmonkeyengine/jme3-jbullet/3.1.0-beta1/jme3-jbullet-3.1.0-beta1.pom
         http://updates.jmonkeyengine.org/maven/org/jmonkeyengine/jme3-jbullet/3.1.0-beta1/jme3-jbullet-3.1.0-beta1.jar
         http://nifty-gui.sourceforge.net/nifty-maven-repo/org/jmonkeyengine/jme3-jbullet/3.1.0-beta1/jme3-jbullet-3.1.0-beta1.pom
         http://nifty-gui.sourceforge.net/nifty-maven-repo/org/jmonkeyengine/jme3-jbullet/3.1.0-beta1/jme3-jbullet-3.1.0-beta1.jar
     Required by:
         :jMonkeyEngine-sdk:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.05 secs
```

**Comment by normen** [comment]
I can run 3.0 no problem on Sierra btw.

**Comment by muellermartin** [comment]
@normen Do you have Java 8 installed?

**Comment by normen** [comment]
The 3.0 SDK comes with Oracles JDK 1.7 included.

**Comment by MeFisto94** [comment]
I want to comment on that again, sorry that it has been so long.
The build issue should be fixed in the most recent versions and building stable (3.0) won't work as the tag is just wildly set and there is no code in this repo for 3.0, it actually starts post 3.0 I guess.

We now also have a 3.1.0-stable tag anyway

**Comment by grizeldi** [comment]
So, close this?
