### ISSUE TITLE
Sample Scene

### ISSUE THREAD

**Issue by Reisbrot** [jMonkeyEngine/sdk#101]

**Comment by Reisbrot** [comment]
Oops sorry pressed Enter
In the documentation on the page
https://jmonkeyengine.github.io/wiki/jme3/beginner/hello_asset.html
is it not possible to load the Town.zip sample scene, Google will say there is no file


Fit it in here? I hope
~Corn

**Comment by MeFisto94** [comment]
Hey,
This is related to jMonkeyEngine/jmonkeyengine#565, but I'll keep this open for now so we have an active issue to be reminded of.

As a temporary fix you can surely make use of the file that Ali_RS provided threre.
I'm also tagging @davidB for jMonkeyEngine/wiki team since it has to be adjusted there as well.

Actually we could really use github for such stuff but unfortunately you'd need git LFS for some files since they are over 100MiB. I'm still uncertain about the legal terms of bintray though

**Comment by Ev1lbl0w** [comment]
I think you can also add jme3-test-data.jar library to your project and continue the tutorial normally, since town.zip was added to the test-data lib.

**Comment by mitm001** [comment]
This has been fixed. This issue should be closed.

**Comment by grizeldi** [comment]
@MeFisto94 looks like this needs closing
