### ISSUE TITLE
Executables on release don't run

### ISSUE THREAD

**Issue by Pesegato** [jMonkeyEngine/sdk#103]
On my Windows 7 x64, I've downloaded the 3.1-beta2-b001-SNAPSHOT jmonkeyplatform.zip, then started the `bin/jmonkeyplatform64.exe` and got this:

![image](https://cloud.githubusercontent.com/assets/8915763/20750376/c2b736dc-b6f6-11e6-92f5-4b0541b713a8.png)

Which translate roughly in: "this executable isn't compatible with the OS. Please check if you need 32bit or 64bit"

Also `bin/jmonkeyplatform.exe` does the same.

**Comment by Ali-RS** [comment]
Did you try jmonkeyplatform-windows-x64.exe  also?

**Comment by Pesegato** [comment]
That one worked, but on about I see:

Product Version: jMonkeyEngine SDK 3.1.0-beta2-b001-SNAPSHOT
Updates: Updates available to version NetBeans 8.1 Patch 1

Wasn't it supposed to be based on Netbeans 8.2?

**Comment by Ali-RS** [comment]
> Wasn't it supposed to be based on Netbeans 8.2?

Yep
Just to get sure can you please check this also : 
![screenshot_2016-11-30_18-47-32](https://cloud.githubusercontent.com/assets/5787647/20758696/dffade18-b72f-11e6-95d9-6dcab3dc4904.jpg)

**Comment by Ali-RS** [comment]
If it is on netbeans 8.1 then i think @MeFisto94 has forgotten to remove the previous netbeans folder before building the sdk ? (So build script skipped downloading new netbeans)

**Comment by Pesegato** [comment]
Apparently, I am sure

![image](https://cloud.githubusercontent.com/assets/8915763/20786446/62e1a070-b7a6-11e6-84d5-06ae05a42123.png)

Has Travis trolled you?

**Comment by MeFisto94** [comment]
Well yes, master should still be 8.1 travis wise, but I _thought_ that each tag has it's own cache and hence I would expect beta2 to use 8.2. In addition to that it uses engine version beta1 (https://travis-ci.org/jMonkeyEngine/sdk/builds/179301297#L764). That's a strange thing I have to check out but I guess this can be solved by just removing travis' cache (And hoping that re-building everything doesn't take multiple iterations due to running out of disk space...)

However https://travis-ci.org/jMonkeyEngine/sdk/builds/179301297#L219 shows it had troubles with my specification of the beta2, so I wonder how it could fall back to beta1?

Anyway this should be unrelated to the bug itself and even worse: I had an idea where that error comes from, but since this also happens for netbeans 8.1 and it also happened for beta1, I am clueless.

If someone is bored and has a fast connection he can try out everything roughly between may and beta1, somewhere it starts to break. 😛 

Usually those exe files shouldn't change at all, possibly not even between netbeans versions.

**Comment by Pesegato** [comment]
I can confirm that 3.1-beta1_unstable-SNAPSHOT works (i.e. the executable is not affected by the bug)

**Comment by Pesegato** [comment]
3.1-beta1-b002-SNAPSHOT **is affected by the bug**

**Comment by MeFisto94** [comment]
I have tried to investigate on that one and for some reason, the files are simply broken:
```$ file working/jmonkeyplatform/bin/jmonkeyplatform.exe 
working/jmonkeyplatform/bin/jmonkeyplatform.exe: PE32 executable (GUI) Intel 80386, for MS Windows
```

```$ file beta2/jmonkeyplatform/bin/jmonkeyplatform.exe 
beta2/jmonkeyplatform/bin/jmonkeyplatform.exe: MS-DOS executable
```
In addition to that, objdump says Unknown File Type for the broken files. I tried to look at the hex diff but apart from some zeroed out regions.

Using https://github.com/jMonkeyEngine/sdk/compare/3.1-beta1_unstable-SNAPSHOT...3.1-beta1-b002-SNAPSHOT (Thanks @Pesegato for your hint) I could find the problem:

It's 5acbb89. For some reason gradle destroys the binary file. I never liked that task anyway, but it is better than a platform dependent bash/awk script.

I have a locally working solution which is even much faster (4 times as fast at least :
