### ISSUE TITLE
HiDPI support on linux

### ISSUE THREAD

**Issue by kmare** [jMonkeyEngine/sdk#112]
I know HiDPI support is a problem with Java up to 8 (Java 9 should finally fix that) but is there a workaround to be able to use the editor without having the need to pull our eyes out? IntelliJ Idea works fine on HiDPI on my linux 4k laptop.

Thank you for your great work and any help!

**Comment by MeFisto94** [comment]
I googled a second and found:
https://jaxenter.com/netbeans/hidpi-with-eclipse-and-netbeans (We already have the dpiaware switch)
and https://wiki.archlinux.org/index.php/HiDPI#NetBeans

What you can do is try the `Netbeans` Theme (Instead of the dark one). Maybe we set a constant font size. If that doesn't work, you can try those font size settings.

In general if you google, do so for `netbeans` instead of `jMonkeyEngine sdk`, as all these suggestions apply to the sdk.

The thing is on my MacBook Retina (Only 2800x...) I don't notice any problems. Maybe it is Linux-only related?

**Comment by kmare** [comment]
First of all, thank you for your input.
The issue is not only with linux but also with windows, it's really a Java problem that is supposed to get a proper fix with version 9 to be released this summer. 
I changed the font size from the command line and it is better for sure, only problem is that the icons are truly small. But I guess I will live with that for a little while till there's a proper solution from upstream.

**Comment by grizeldi** [comment]
With java 9 out for a while now, what can we do about this? Wait for next netbeans release?

**Comment by MeFisto94** [comment]
Yeah, that's the only reasonable solution. It might be possible to run netbeans 8 in a Java 9 JRE, but that's definitely not so recommended.

4 days ago Netbeans 9.0 started entering Beta it seems but don't expect the SDK to immediately switch either, because I expect bigger changes with 9.0 as it also seems the project is now held by Apache instead of Oracle. This also means we have to check if they're not going to release it under their APL.

**Comment by tlf30** [comment]
Just wondering on a status update for this issue. Apache netbeans is now in incubation (although I personally have not used it yet)

**Comment by tonihele** [comment]
This is probably now ok with Netbeans 12 as base finally. The HiDPI things came in Netbeans 11 as far as I can remember.

**Comment by tonihele** [comment]
This is working as far as I know. We are in the process of making the icons scale nicer, so yeah :)
