### ISSUE TITLE
Loading splash image still says SDK 3.1

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#124]
Just a minor issue. Although the latest SDK is running on jme 3.2, the splash image still says jMonkeyEngine SDK 3.1.

**Comment by MeFisto94** [comment]
The problem is there is no source file at least not in this repository, see here https://github.com/jMonkeyEngine/sdk/tree/master/branding/core/core.jar/org/netbeans/core/startup

There is only the splash.gif, but I think someone posted a psd to the hub? Or at least did the splashscreen, @Dokthar ?

I'm also tagging @Nehon since he actually commited the new images
