### ISSUE TITLE
jMonkeyEngine SDK installer fails on MacOSX 10.5

### ISSUE THREAD

**Issue by erlend-sh** [jMonkeyEngine/sdk#13]
_From @ghost on March 24, 2014 19:34_

Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=198

> The installer of jMonkeyEngine SDK Alpha-2 fails to run on MacOSX 10.5 because it falsely tries to use Java 1.5 to start the installed.

> Workaround:
> If you have Java 1.6 installed on your computer you can temporarily rename the Java 1.5 folder in /System/Library/Frameworks/JavaVM.framework/Versions/ to some other name like "1.5backup" and run the installer. After installing the folder can be renamed back to "1.5".

_Copied from original issue: jMonkeyEngine/jmonkeyengine#10_

**Comment by erlend-sh** [comment]
_From @empirephoenix on September 23, 2015 12:14_

I believe this problem has died out together with java 1.5 right?

**Comment by normen** [comment]
The NBI installer for OSX is still wonky in terms of what JDK it tries to invoke. More of a NetBeans/NBI issue though.

**Comment by grizeldi** [comment]
Maybe it works with netbeans 8.1?

**Comment by MeFisto94** [comment]
Well, this issue is from 2010 and since OSX 10.6 has been released on 28.8.2009 and Java 6 has been released in 2006 we can close it because it's irrelevant now.

I've had no problems with the installer on 10.9.5 and it comes shipped with the jdk bundled (I don't know if that was the case in 2010?)

Btw: I doubt that a newer netbeans cares about such old systems, it's like trying to run the installer on dos :P (However I'd be curious to see what it does on w95/98)

So if you experience any problems, feel free to create a new issue then.
- MeFisto94
