### ISSUE TITLE
SceneComposer: DirectionalLight isn't updated in 3D view after direction is changed

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#144]
The representation of the DirectionalLight (the arrow pointing in the same direction as the light) isn't updated until a scene is reloaded when you change the direction in the properties.

**Comment by MeFisto94** [comment]
I've solved this problem but it wasn't so easy.
That's because the SceneEditTools aren't made to have edits from the outside that much.
SpotLights do update their gizmo but they behave strangely particularly ignoring the sign (0, 1, 0) == (0, -1, 0).

Strangely I cannot find any code which updates the SpotLight's Gizmos (haven't done much searching though).

Note that sometimes the Directional Light rotating is bugged after you manually specified a direction. This seems to be some internal state which has to be reset. I fixed it by changing between the selection and rotation tool (by clicking their buttons) and trying to rotate it a bit.
