### ISSUE TITLE
Set default shadow mode for nodes and geometries to CastAndReceive

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#169]
For some unknown (probably legacy) reason, when you create a new node, or new anything in SceneComposer, it's shadow mode is set to off by default. In 2018 gpus really shouldn't have problems with shadows and therefore the default mode should be CastAndReceive. Usually you have waay more models that should have shadows than ones that don't.
If there actually is a reason to keep default to Off, there should at least be a setting for a manual override.

**Comment by MeFisto94** [comment]
A quick investigation showed:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/scene/Spatial.java#L1287

This means: When all Spatials are set to inherit (which they are by default), then they all will be "Off" because the rootNode has no parent. It is up to the engine guys to discuss if this behavior is desired or not.

What is a fault of the SDK is to not call `getLocalShadowMode` instead, though I must say this feels misleading (because in most times you care about the "local" shadowMode, the "world" shadowMode is more for the renderer). After that fix they are set to Inherit.

What has to be done afterwards is making the rootNode CastAndReceive or leaving it like that (in which case the user would have to enable it on a per-scene base. Otherwise the results would be different than to the engine because a regular rootNode also comes with ShadowMode.Inherit

**Comment by grizeldi** [comment]
What we can make though, is edit the root node in the file that is copied when you go "New > j3o Scene" to have CastAndRecieve. Since shadow modes usually become relevant in bigger scenes which at least I personally make with "New > j3o Scene".

**Comment by MeFisto94** [comment]
Sounds like a good compromise, then it'll magically work in the engine as well :D The question is if we should edit the template file or just apply this "fix" in code. if you're bored, https://github.com/jMonkeyEngine/sdk/blob/master/jme3-scenecomposer/src/com/jme3/gde/scenecomposer/Scene.j3o
