### ISSUE TITLE
Add a edit terrain button to terrain nodes in scenegraph explorer

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#17]
When I'm using scene composer I often find it annoying that I have to right click the scene j3o file instead of the actual terrain node.
I think that it would be way more logical to have the button available in the terrain node right click menu.

**Comment by MeFisto94** [comment]
Quoting @normen's argument
> Theres a big button in the top bar to open the terrain editor. I don't think it makes sense to put it in the Scene Explorer because that is where self-contained actions for the Scene Explorer live (i.e. across all editor plugins).

Granted though that the right click on the Terrain Node might be more intuitive.
What happens when you have multiple Terrain Nodes in one .j3o? (Is it even possible?)

**Comment by normen** [comment]
The TerrainEditor will only edit the first one - making this again less intuitive. Generally you should use multiple j3o files for such a case though. Its not like one j3o is meant to store your whole game. And if it was used for multiple terrains then there would be one TerrainEditor to edit them. The TerrainEditor opens *j3o files*, not single Spatials within j3o files. So I still don't agree it would be intuitive to open them via the SceneExplorer. Its like opening a folder by specifying a file inside - not intuitve.

**Comment by MeFisto94** [comment]
Okay,
Since it's really better to have one .j3o file per Terrain (and rather link them together) and since there's the Terrain Icon, it's quite fast to switch into it then (without having to search the j3o in Project Assets).

Actually the Terrain Editor and the Scene Composer are different things and you could even run the SDK without the Terrain Editor, it might not be useful to link them together.
