### ISSUE TITLE
v3.2.2-stable-sdk1 installation fails with NullPointerException in ConfigurationLogic

### ISSUE THREAD

**Issue by James-Richardson** [jMonkeyEngine/sdk#186]
Every time I try to install v3.2.2-stable-sdk1, it fails and rolls back. The exception in the log file is:

java.lang.NullPointerException
	at org.mycompany.ConfigurationLogic.setExecutableContents(ConfigurationLogic.java:215)
	at org.mycompany.ConfigurationLogic.install(ConfigurationLogic.java:202)
	at org.netbeans.installer.product.components.Product.install(Product.java:358)
	at org.netbeans.installer.wizard.components.actions.InstallAction.execute(InstallAction.java:155)
	at org.netbeans.installer.wizard.components.WizardAction$1.run(WizardAction.java:123)

**Comment by James-Richardson** [comment]
The line in question is calling File.listFiles(). As [pspeed points out in the forum](https://hub.jmonkeyengine.org/t/next-release-s-of-the-engine/40856/122?u=jamesrichardson), this method returns null if the File is not a directory.

v3.2.1-stable-sdk3 installed correctly for me. The log file for this install is here: https://www.dropbox.com/s/wxo134sksc9d2re/20180906195736.log?dl=0

The log file for one of the failed v3.2.2-stable-sdk1 installs is here: https://www.dropbox.com/s/5g3me1p5h44cqsq/20190101203940.log?dl=0

According to the exception stack trace, it is calling setExecutableContents for "db/bin". Looking at the log file for the v3.2.1 install, at line 13019, I see that it is copying files to C:\Program Files\jmonkeyplatform-3.2.1\jdk\db\bin. However, looking at the log file for the failed v3.2.2 install, although it does copy files to C:\Program Files\jmonkeyplatform-3.2.2\jdk, it never copies anything to do the db folder.

So, my guess would be that the db/bin folder isn't being created, and so "db/bin" isn't a directory, which is why File.listFiles() returns null.

**Comment by MeFisto94** [comment]
One question, as paul mentioned this being a permission issue in most cases (and we didn't really change something in that code, iirc): Did you run the installer as Admin? Does it work when installing to your user folder etc?

**Comment by James-Richardson** [comment]
My user has admin privileges. I tried installing it to my user folder instead, and I tried right-clicking on the executable, and selecting "Run as administrator", but it still doesn't work. Note that the installer does create the jmonkeyplatform folder, and a load of subfolders and files beneath it. So, it does have permission to create files and folders wherever I'm telling it to.

**Comment by MeFisto94** [comment]
I wonder if this happend once before, see this commit: https://github.com/jMonkeyEngine/sdk/commit/c9440bd5ea7db701d54970c9971f5b7e761faec1#diff-22449563978c24e1fc2bd62941f10412
Also relevant is maybe this commit: https://github.com/jMonkeyEngine/sdk/commit/03f655680376725862d657bbb1119bdf6ab3b211#diff-4b8bcd8f3038cf9ff3548842d9294d2c
and
https://github.com/jMonkeyEngine/sdk/commit/278e5a5dd9b75ae9c9100ed3384890342e86f4f3

I guess that the new jdk does not come with a db/bin folder anymore, and thus the code simply fails. The question is whether we should fix that exception or rather just adopt to the folder structure of the new jdk, I'm thinking of the latter because that way we are notified when something changes there.

Okay a bit more research has been done:
db is Apache Derby, a relational database, which will be dropped in Oracle JDK 9, https://blogs.oracle.com/java-platform-group/deferring-to-derby-in-jdk-9
Now I wonder if they also did that for 8u192b12 already instead of 9?

Okay that's it: https://www.oracle.com/technetwork/java/javase/8all-relnotes-2226344.html?printOnly=1 [Caution, site is loading quite a long time]
Derby has been removed as of JDK8u181 in July 17, 2018

**Comment by MeFisto94** [comment]
One question, as paul mentioned this being a permission issue in most cases (and we didn't really change something in that code, iirc): Did you run the installer as Admin? Does it work when installing to your user folder etc?
