### ISSUE TITLE
Windows cannot find the target

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/sdk#187]
Using the fba0229 build of `v3.2.2-stable-sdk1` on a 64-bit Windows7 platform, I try to open a project. Before the file chooser dialog box appears, multiple error alert boxes appear, each containing the message "Windows cannot find the target".

**Comment by stephengold** [comment]
I see more of the same alerts when I try to add a plugin using the "Add plugins..." button in the "Downloaded" tab of the "Plugins" box. These alerts seem to appear any time I use a file chooser.

I never had this issue with `v3.2.1-stable-sdk3` so it must be related to a recent change.

**Comment by MeFisto94** [comment]
This is a really strange issue, someone else is having it in Netbeans 9.0 but since it also appears in Word, it seems like coming straight from the OS.
http://mail-archives.apache.org/mod_mbox/netbeans-commits/201812.mbox/%3cJIRA.13193793.1540371058000.72542.1543710120111@Atlassian.JIRA%3e

Do you have dead shortcuts on your desktop? and if so maybe the dialog occurs exactly the number of times you have dead shortcuts on your desktop? Do you get to the file chooser eventually after clicking the alert boxes?

MS suggests that your userprofile is broken, but I wouldn't give this too much trust: https://answers.microsoft.com/en-us/windows/forum/windows_7-files/cannot-explorer-users-folder-cannot-download-files/2a7d248e-77aa-4c6f-9569-62b3faf2cbff

What I COULD imagine (as you say it only appears now), is that the JDK Version is at fault, seeing that you use the exactly same JDK Version as the others on the issue tracker.
You can try to change it here: https://stackoverflow.com/a/6958342 I'm pretty sure you have some older jdks lying around on your system.

**Comment by stephengold** [comment]
I have dozens of shortcuts on my desktop. A few could be considered "dead" because they point to files on CD-ROMs and such that aren't inserted at the moment. I haven't counted the "dead" shortcuts.

I want to keep those shortcuts handy, though I suppose I could move them to a subfolder to get them off the desktop.

I did get a file chooser eventually.

**Comment by stephengold** [comment]
I moved all my desktop shortcuts to a folder on another drive, but I still have this issue.

**Comment by stephengold** [comment]
Editing `etc\monkeyplatform.conf` as administrator in order to change the setting of `jdkhome` seems to have solved the issue for me. I pointed it to the JDK from 3.2.1-sdk3. Is there any possibility of reverting the JDK version to the one used in 3.2.1-sdk3?

**Comment by MeFisto94** [comment]
Because of Travis we cannot really get back to the old version without trouble because Oracle only hosts the last two versions of java 8 jdks only since they want to push java 11 now.

Maybe you can try https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html (Version 201 or 202) to see if that fixes it as well?

**Comment by stephengold** [comment]
I tried updates 201 and 202. Neither one resolves this issue.

**Comment by stephengold** [comment]
I'm up and running with update 161; some update between 161 and 201 broke the SDK. 

I found this archive of old JDK/JRE versions. Perhaps it will be of some help to us:

 https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html

**Comment by stephengold** [comment]
I created an account at Oracle.com and downloaded/installed/tested a bunch of old JDKs. I discovered that the issue was introduced between 1.8.0u181 and 1.8.0u191. Not sure if that helps any.

**Comment by stephengold** [comment]
I tried to reproduce this issue using the e20399c748514d47dc112f35aefa205dc9fe3f1d build of v3.2.3-stable-sdk1 and failed, so I believe it is fixed.
