### ISSUE TITLE
SDK : "Error finding blender settings" 

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/sdk#20]
When building SDK it downloads Blender 2.76 which is assigned in 
`nbi/stub/ext/infra/build/products/blender-windows-x64/build.properties`   also for Mac and Linux 
but blender 2.75 being located in `sdk/jme3-blender/src/com/jme3/gde/blender/BlenderTool.java `

`File blender = InstalledFileLocator.getDefault().locate(getBlenderOsSettingsPath() + "/2.75", null, false);`
So when i double click on a .blend file in sdk i get this error "Error finding blender settings".

**Comment by MeFisto94** [comment]
Good Finding!
Did you run a search through the source to see if this also happens in other files? (as in launching blender etc)?

**Comment by Ali-RS** [comment]
Thanks for fast reply.
Only where i could find which has reference to blender 2.75 was `sdk/jme3-blender/src/com/jme3/gde/blender/BlenderTool.java`
It called 2.76 . I actually downloaded it from release part which you provided.but isn't supposed to be 2.76b?
for now I replaced the blender folder with blender 2.75 from JME 3.1 alpha 1 ant it is working.

**Comment by MeFisto94** [comment]
I've also checked the references and you're right, it was the only.
It seems to me that blender calls it's settings folder only after the major version, so ´2.76 a-z` will all have the 2.76/ folder.

Btw: a more clever workaround would've been to rename it from 2.76 to 2.75 (though it could be that blender doesn't wants to startup then :P)

I'll make an official release anytime soon when I've fixed some different things (Since the full build takes > 1 hour and we don't want to stress the servers too much :P)

**Comment by normen** [comment]
Yes, the smart way would be to rename the folder in all blender imports in the NBI importer to a generic name like "original" (i.e. scripts/original in the folder structure) - that was actually the plan. Should work fine because blender gets the scripts folder location as a parameter when started up (which is also why it fails in the first place).

**Comment by Ali-RS** [comment]
Renaming from 2.76 to 2.75 does not work. it gives error "blender has stopped working".

**Comment by MeFisto94** [comment]
Now this is really strange, just to get that straight:
Running Blender 2.76 with a copy of 2.75's settings folder works however
Running Blender 2.76 with the 2.76's settings folder (renamed) crashes?

Do you have any log output inside of the sdk when blender crashes?

btw: From the getScriptsEnv():
```java
//TODO: using installed blender scripts folder
        String ret = getBlenderSettingsFolder().getAbsolutePath();
//        String ret = System.getProperty("netbeans.user") + "/" + scriptsFolderName;
        ret = ret.replace("/", File.separator);
        return ret;
```
shouldn't the scriptFolderName be appended to the blenderSettingsFolder anyway?
And I'll try to make it independant of the version :)

**Comment by Ali-RS** [comment]
Just got this in output:
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
```
I just renamed folder name from "2.76" to "2.75" . Did not changed any other settings.

**Comment by MeFisto94** [comment]
Can you maybe see differences between the folder's contents?
Googling comes up with a wrongly set [https://mail.python.org/pipermail/python-dev/2012-October/122360.html](PYTHONPATH)

**Comment by Ali-RS** [comment]
Yes Both the "lib" folder and "bin" folder have some differences. I will try to replace them to see if i can make it works.

**Comment by MeFisto94** [comment]
Also try to only rename the lib folder to lib64.
It's a really strange issue but it happens [sometimes](https://developer.blender.org/T35785)

**Comment by MeFisto94** [comment]
Okay so I investigated it further in order to fully understand what's going on.
The thing is: When you rename the folder then the user won't be able to run blender on his own (because you need to reset multiple Environment Variables).

I think the a thing would be to run a search against the RegEx Pattern `\d.\d\d` since I've checked: Even back in 2000, it was `blender 2.01` instead of 2.1
If it would break somewhen it's not hard to change that pattern but I highly doubt this will ever happen.

However I don't feel the need of setting that variable at all?
Same with the Config. Why should it make a difference if you launch blender on your own or from jMonkey?

The only thing that I'll keep will be the userscripts, because that's where further xbuf versions could be placed. That way it will only work when the SDK is also running. 
However copying blenders system scripts or having it place the preferences in a jmonkey folder instead of its own isn't very reasonable to me.

I'll keep it in code though, so we can revoke that any time when there's a reason to do this.
