### ISSUE TITLE
 jMonkeyEngine SDK installer fails on MacOSX 10.7

### ISSUE THREAD

**Issue by Dokthar** [jMonkeyEngine/sdk#27]
_From @ghost on March 24, 2014_

Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=401

_Copied from original issue: jMonkeyEngine/jmonkeyengine#43_

**Comment by MeFisto94** [comment]
I actually tried this out just now.
The Problem is the installer is searching for a jdk/jvm to launch off.
We _do_ bundle a JDK but that cannot be accessed since it is inside of the .jar (plus the JDK might even be pack200 compressed).

This used to work it seems? I'd say we have a problem in how we process the .zip but actually it's no fun to fix that in the Installer :( 

I'd say we just tell the people to install a jdk for now. It might even be shipped with newer Mac OS Systems.

**Comment by normen** [comment]
No it never used to work, the installer always used to call the installed system JVM, the SFX-solution of NBI never worked on mac.

**Comment by MeFisto94** [comment]
Yeah and then we gave up the SFX and simply zip the jdk instead and "do some things" which I didn't dig into further.
But that zip isn't in the Resources Folder (if it is there, it's in the jar) and I don't know if the Installer would use the zip if he has found it.

So the question is: Is it only wrong packaging of the jdk zip or is there more missing?

_Personally I think someone who wants to develop a Game using Java should be able to download a working JRE so he can atleast launch the installer._

**Comment by grizeldi** [comment]
@MeFisto94 I agree with that last part. Actually a person who wants to develop a game in whatever language (scratch, app inventor and other beginner tools not included) should be able to download and install JRE.

**Comment by normen** [comment]
The JDK for MacOSX is a "product" installed by the installer (like blender), this isn't "wrong", it just doesn't work for using the same JDK to run the installer. The built-in function to do that simply doesn't work on OSX as I said.

The workaround is using the installer to install the SDK on a system that has a JDK installed and zipping up the resulting folder so OSX users get a zip file with the SDK application inside. I was hoping they'd fix the "use included JDK to run installer" for OSX at some point but two versions later that still didn't happen. Thats why OSX basically uses the same way to create an installer still.

In theory one could create that zip file "manually" in the build process, downloading the JDK and Blender for OSX and putting them in the appropriate places inside the .app package. That'd require an even more special build target for OSX though.

As for users being able to install a JDK the reasons for including the JDK are
a) In fact some are not able to do that properly, even if they're developers they might not be Java devlopers. Some people get confused in the download screen and download the NetBeans/JDK package and whatnot.
b) Compatibility of jME with different JDKs is not always given. Bundling it makes sure a compatible version is installed. Especially on Linux the various OpenJDK bundles often caused issues with the SDK, the engine or the deployment. Java8 broke jME for a while due to some API changes etc.
c) The SDK becomes a self-contained application.

**Comment by grizeldi** [comment]
I don't know how many general OSX issues are in play here, but OSX 10.7 is more than 6 years old and no one should be using it by now probably.

**Comment by MeFisto94** [comment]
Yeah, even I upgraded from 10.9.5 recently :D 
And if not people can still comment here.
