### ISSUE TITLE
LightPosition and LightColor WorldParams don't seem to supply a value

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#332]
When I use the LightPosition or LightColor WorldParams in a ShaderNode, all I get is a black output. If I instead add a MatParam to supply values, I get the expected result (light, color).

**Comment by neph1** [comment]
I've tried looking into this, but any hint where to look would be appreciated :)

**Comment by MeFisto94** [comment]
Not really a hint, but it sounds like this is an engine problem technically? Like it's related to ShaderNodes themselves and not the Editor or something?

I guess I would try to look at the generated shader, because technically these world parameters are supplied by jme much like mat params, so the question is mostly if they are defined correctly (e.g. `g_LightColor` or however they are called).
In theory one could also add test-cases for such basic things to [MeFisto94/jme3-testing](https://github.com/MeFisto94/jme3-testing)

**Comment by neph1** [comment]
Yeah, i just thought that since it seems to work for the material editor,
shader nodes would use the same basis. And someone in the forum said they
thought it worked at some before. But then I might do something of my own
to solve it.

**Comment by neph1** [comment]
NM! LightColor and LightPosition shouldn't be used for PBR. g_LightData is magically supplied to the shader.
