### ISSUE TITLE
Add a control pause button to scene editor

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#34]
Add a button to scene editor that pauses/resumes all controls in the scene so that moving spatials don't run away.
See:
http://hub.jmonkeyengine.org/t/sdk-maintenance-plan/35259/30

**Comment by MeFisto94** [comment]
<img width="331" alt="control_stop" src="https://cloud.githubusercontent.com/assets/12577813/13821502/3e20a6da-eba2-11e5-862c-324097e22244.png">
<img width="331" alt="controls_stopall" src="https://cloud.githubusercontent.com/assets/12577813/13821501/3e1c10ac-eba2-11e5-94b1-8aba2e753205.png">

I have implemented them as SceneExplorer Context Menus now actually because:
a) There was no way to start/stop single Controls
b) To emphasize how Stop All works (it simply iterrates through all children and stops it's controls)

**Comment by Dokthar** [comment]
@MeFisto94 what's the default behavior ? I think controls should by default enabled.

**Comment by MeFisto94** [comment]
They actually are.

**Comment by grizeldi** [comment]
That is exactly how I imagined it, thanks!

**Comment by MeFisto94** [comment]
Note: Due to problems, I'll push another commit soon.
It will only work for AbstractControls and Descendants. Not sure how it is with internal controls, but since you use that for own Controls most of the time it shouldn't be a problem then.
