### ISSUE TITLE
Upgrade "Code Checks" to use Hint over AbstractHint

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#37]
The Code Checks Module is relying on a deprecated Netbeans API:

```
jme3-code-check/src/com/jme3/gde/codecheck/hints/TempVarsHint.java:20: warning: [deprecation] AbstractHint in org.netbeans.modules.java.hints.spi has been deprecated
[ant:nb-javac] import org.netbeans.modules.java.hints.spi.AbstractHint;
```

The thing is, we have to upgrade from `extends AbstractHint` to `implements Hint`
See [here](http://www.grepcode.com/file/bits.netbeans.org/maven2/org.netbeans.api/org-netbeans-spi-java-hints/RELEASE80-BETA/org/netbeans/spi/java/hints/Hint.java#Hint)

Actually we don't have to Implement the Hint but rather uses it's Annotations.
This unfortunately is more than a small refactoring. See [here](https://platform.netbeans.org/tutorials/nbm-java-hint.html)

It seems to be Deprecated in 8.0 so it's really low priority, but when you want to learn a bit about Netbeans API and do some chilled refactoring, this one is for you :)

**Comment by grizeldi** [comment]
This one looks interesting. I'll try to do it when I have some time.

**Comment by grizeldi** [comment]
Just checked the code. I'll see what I can do.
And if I'm already working on it, can I move the strings to bundle.properties?

**Comment by MeFisto94** [comment]
Sure you can, this is actually even prefered since it allows you to add localization to the SDK

**Comment by grizeldi** [comment]
When is ReadOnlyPrimitives supposed to fire? Can't get it to work on geometry.getLocalTranslation().set(blah blah blah). Maybe I screwed up something in the part where I moved id strings to the bundle. I'll check tomorrow.

**Comment by grizeldi** [comment]
Hmm... Checked the id string and it should work. Now I guess I'll try to build a clone of this repo to see if it works here. Otherwise I just found a new bug.

**Comment by theom** [comment]
This still seems to be an issue so I'll try and take a stab at this.

**Comment by theom** [comment]
Sorry, bailing out. This is too big of a chunk for me at the moment.

Some pointers to keep in mind when fixing this:

* If you are new to NetBeans hints then I strongly suggest you go through the [tutorial](https://platform.netbeans.org/tutorials/nbm-java-hint.html) MeFist94 mentions. It will at least get you going in the right direction.
* Use the hints wizard to create the skeleton class for each hint (like in the tutorial). In the wizard you enter most of the text the hint shows so no manual editing of property files needed.
* The hint flow is something like this:
  1. The TriggerPattern annotation is used to find the code to hint on. There is also a TriggerPatterns (plural) that can contain multiple TriggerPattern entries which is useful if you want to match on multiple patterns in the hint.
  1. The annotated method is passed a context containing the (partial?) AST of the code matching the TriggerPattern.
  1. The return value of the method is used by NB to decide if a hint should be shown or not. If null is returned no hint is shown.
  1. A 'code fixer' can be added to the return value that NB calls if the user chooses to let the hint fix the code.

I got the UpdateHint working but got stuck when implementing the TempVarsHint. I was simply unable to construct a TriggerPattern that got me what I wanted (a reference to the TempVars variable) and since I did not find any useful TriggerPattern documentation or examples it just got too frustrating. I'm sure the massive NB code base has some clues on this but digging around in there is not something I want to spend my time doing.

The idea was then, once I got my hands on the TempVars variable, to basically do the same as in the current TempVars hint to walk the AST looking for the release() method. I don't think it's possible to cascade annotated hint methods to find the release() method so a manual AST walk is probably unavoidable.

Hope this helps.

**Comment by tonihele** [comment]
I think this can be closed. Done via https://github.com/jMonkeyEngine/sdk/pull/221.

I also hope this might affect: https://github.com/jMonkeyEngine/sdk/issues/142. Something hint related. So this is just a long shot...

Performance I expect to be pretty much the same, unless the newer module speeds things up a bit. I did try to avoid some unnecessary stuff the old did. And the TempVars hint was not thread safe (though I don't know is that a requirement for the hints), now it is. I guess it tried to avoid always creating an ArrayList just used in scanning, it also tries to avoid it now. Before it was a class level variable.
