### ISSUE TITLE
Improve Gradle project user experience

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/sdk#382]
Improve Gradle project user experience. We have the new Gradle wizard and all that. It is great. But getting really things started with your new Gradle game template is super tricky.  It needs to be built first to trigger some stuff happening. Even after that, the SDK doesn't recognize it as a jME project and display the Assets folder. A SDK restart is needed. Then one can go on with modeling and all that.

Also double click doesn't edit the file, context menu and Edit is needed to open scene file in the Scene editor.

Painful video evidence:
[Improve Gradle project user experience](https://youtu.be/wCFEPQJSAnI)

**Comment by neph1** [comment]
But, hey! It worked in the end :wink: 
That makes all the effort worth it.

**Comment by tonihele** [comment]
Heh yes, UX to the max.

**Comment by peedeeboy** [comment]
**Re: missing asset node.**  
Something is very strange in the Gradle tooling in the SDK.  When the project is first loaded by NB after creation, the name of the sub-project is returned as "assets".  But on subsequent loads, e.g. after SDK restart, the sub-project name is returned as ":assets".  

I've pushed a workaround in #383 , but the root cause seems to be the SDK Gradle tooling is a bit borked for some weird reason.  Other examples:

Opening a `gradle.build`, with have two `Source` tabs:
![image](https://user-images.githubusercontent.com/44434629/189773053-3dda4b08-9ea7-414d-9bfd-5271251cf478.png)

This doesn't happen in NB15, just the SDK...  

Also, when the Assets sub-project is first loaded, the root directory is correctly identified by Netbeans as a Resource folder (it is declared as such in the root `gradle.build`, and a Resource node created.  But on subsequent loads, no resources node is created:
![image](https://user-images.githubusercontent.com/44434629/189773303-ba5c0bfe-8cff-46f2-b18e-1d068acadc79.png)

Again, things work correctly in NB15:
![image](https://user-images.githubusercontent.com/44434629/189773371-ebf1ffa9-032f-4e50-8fd4-b0e293f4f6dc.png)

**Comment by peedeeboy** [comment]
**Re: Gradle priming build**
IIRC there was a change to NB a couple of versions back to no longer do an automatic priming build on Gradle projects to prevent malious code execution in the Gradle build scripts.  Netbeans now prompts for a priming build with that "Resolve project problems" dialog.

It might be that manually kicking off Gradle builds of the projects in `GradleDesktopGameWizardIterator.Intantiate()` method would be acceptable to NB.  

TBH, I don't really like the unzipping approach to creating the new project - I was always thinking of a Phase 2 to updating the Gradle project template to refactor it to use NBs Gradle tooling to create the Project, and then make necessary changes such as updating the build.gradle etc... If the community can agree on what the *ideal* Gradle template would look like....

**Comment by peedeeboy** [comment]
**Re: double click doesn't edit the file, context menu and Edit is needed to open scene file in the Scene editor.**
I can't remember if this ever worked in Gradle projects?  But my first though would be something wonky in the registration of the NBs Action for SceneLoader, or the registration of the DataObject for BinaryModels where Gradle projects are concerned....

**Comment by tonihele** [comment]
> TBH, I don't really like the unzipping approach to creating the new project - I was always thinking of a Phase 2 to updating the Gradle project template to refactor it to use NBs Gradle tooling to create the Project, and then make necessary changes such as updating the build.gradle etc..

This sounds good. I think I have seen this approach talked in Netbeans as well, that Gradle itself should be leveraged to create a new project and all that. The API just probably would do this. So it would always be somewhat up-to-date. Of course we must have some kind of control over it.

**Comment by tonihele** [comment]
I guess it is ok to close this.  Better to create more specific issues for other remaining cases. Now the root cause is fixed (didn't test).
