### ISSUE TITLE
Tips for improving the Material editor

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#519]
I opened this Issue to keep track of forum discussions to improve the Materials editor.

https://hub.jmonkeyengine.org/t/sdk-material-editor/46697

![Material Editor](https://github.com/jMonkeyEngine/sdk/assets/32201701/7469c255-d129-461b-abad-ca0fdd3b7918)

**Comment by neph1** [comment]
I'm a bit reluctant to go back to the old style tab views for properties, since I like the option to have everything visible on large screens. But I'm thinking perhaps we could do something with collapsible tabs? Not sure if there is anything built into Swing, but shouldn't be that hard to implement.

**Comment by capdevon** [comment]
Hi Rickard, I am glad you are working on improving the editor. AFAIK, there is no collapsible panel in Java Swing. Maybe you can find one already built with some external library.

**Comment by neph1** [comment]
I've made the panels a bit more flexible: https://github.com/jMonkeyEngine/sdk/pull/531

**Comment by neph1** [comment]
@capdevon Please check the latest SDK release and see if you find the panels improved.
