### ISSUE TITLE
SDK doesn't install on Linux x64

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/sdk#57]
I'm trying to install the latest linux64 release on Kubuntu 14.04, but when i click the first NEXT the installer quits with this error

```
[Error] wizard.xml.1:43:10: cvc-complex-type.2.4.b: The content of element 'wizard' is not complete. One of '{component}' is expected.
```

I don't know if this happens with the other os releases too.

Full log:

```
Configuring the installer...
Searching for JVM on the system...
Preparing bundled JVM ...
Extracting installation data...
Running the installer wizard...

(java:8110): Gtk-WARNING **: gtk_dialog_set_alternative_button_order_valist : no child button with response id -11.

(java:8110): Gtk-WARNING **: gtk_dialog_set_alternative_button_order_valist : no child button with response id -5.

(java:8110): Gtk-WARNING **: gtk_dialog_set_alternative_button_order_valist : no child button with response id -8.

(java:8110): Gtk-WARNING **: gtk_dialog_set_alternative_button_order_valist : no child button with response id -3.

(java:8110): Gtk-WARNING **: gtk_dialog_set_alternative_button_order_valist : no child button with response id -10.

(java:8110): Gtk-WARNING **: gtk_dialog_set_alternative_button_order_valist : no child button with response id -2.

(java:8110): Gtk-WARNING **: gtk_dialog_set_alternative_button_order_valist : no child button with response id -7.

(java:8110): Gtk-WARNING **: gtk_dialog_set_alternative_button_order_valist : no child button with response id -9.

(java:8110): Gtk-WARNING **: gtk_dialog_set_alternative_button_order_valist : no child button with response id -6.
[Error] wizard.xml.1:43:10: cvc-complex-type.2.4.b: The content of element 'wizard' is not complete. One of '{component}' is expected.
```

**Comment by MeFisto94** [comment]
Yeah, it's known and happens when you try to reinstall the SDK.
For some reason we have an incomplete wizard definition for the reinstallation process which leads to this error.

As a workaround try to delete (or rather rename) existing folders, especially those in ~/.jmonkeyplatform and ~/.jmonkeyplatform-installer

We'll keep this issue open though. I just didn't look into it as I experienced it because the NetbeansInstallers are somewhat fragile :P

**Comment by riccardobl** [comment]
Ah, ok. No problem then i will manually delete the old version :)

**Comment by MeFisto94** [comment]
Hey, 
Did it work that way?

**Comment by riccardobl** [comment]
I initially removed ~/.jmonkeyplatform and it was still crashing, so i removed ~/.jmonkeyplatform-installer and now it works.

**Comment by john01dav** [comment]
Personally, I just install the .zip file to /opt manually then add a .desktop file to ~/.local/share/applications. I'm using Ubuntu 16.04 Beta right now, but I did something very similar on 14.04. 

Here is my desktop file if you want it:
```
[Desktop Entry]
Name=JME SDK
Exec=/opt/jme-sdk/bin/jmonkeyplatform --jdkhome /usr/lib/jvm/java-8-oracle/
Icon=/opt/jme.png
Type=Application
```

**Comment by nordfalk** [comment]
Hi there,
Just as a note for Google - the problem is still present in jMonkeyEngine SDK 3.1.0 Stable.

```
sh jmonkeyplatform-linux-x64.sh 
Configuring the installer...
Searching for JVM on the system...
Preparing bundled JVM ...
Extracting installation data...
Running the installer wizard...
[Error] wizard.xml.0:43:10: cvc-complex-type.2.4.b: The content of element 'wizard' is not complete. One of '{component}' is expected.
[Error] wizard.xml.2:43:10: cvc-complex-type.2.4.b: The content of element 'wizard' is not complete. One of '{component}' is expected.
```

and when I click 'Next' on the first screen on the installer the process ends without further messages.

Solution: Remove .jmonkeyplatform-installer directory.

`rm -rf ~/.jmonkeyplatform-installer/
`

and it works :-)

**Comment by MeFisto94** [comment]
It's hard to tell because it's unclear which wizard.xml is meant and also why this is only critical for updates and not for a clean install, but `./nbi/stub/ext/components/products/blender/src/org/mycompany/wizard.xml` contains an empty `<wizard>`, so it could be possible to fix this by removing the wizard entirely (or making the Blender Installation customizable, which would be more preferable, but requires reworking other parts)

`./nbi/stub/ext/components/products/jdk/src/org/mycompany/wizard.xml` is also affected, it doesn't even contain `<!--component class="org.mycompany.wizard.panels.ShortcutCreationPanel"/-->` like blender does.

I'll try to see if that improves things

**Comment by MeFisto94** [comment]
Okay, I have that working locally, the plan was to remove it for the jdk (it doesn't contain code for said panel) and keep it for blender. For some reason on Mac OS during the upgrade (not sure if it detected the old SDK 3.0), it did not show me the option to create a Desktop Shortcut for Blender. I'll fixing this to see if others see that wizard. If not, it doesn't matter that much I think.

**Comment by nordfalk** [comment]
Cool!
I'll try to do a fresh install when a new version is released to check if it works now.

**Comment by lsms1990** [comment]
[https _www.apple.com_icloud_.pdf](https://github.com/jMonkeyEngine/sdk/files/1791363/https._www.apple.com_icloud_.pdf)
