### ISSUE TITLE
Avian won't extract when enabling IOS plug in.

### ISSUE THREAD

**Issue by AnthonyWilshaw** [jMonkeyEngine/sdk#58]
The avian-openjdk folder doesnt install itself when switching on the IOS plugin for the first time.

**Comment by MeFisto94** [comment]
This is known. The Problem is we're currently unable to build avian ourselves, there are multiple errors and we don't have many mac guys. 
You can try to build it by yourself, see the docs folder in this repo and the forums, maybe you can get it to work.

**Comment by AnthonyWilshaw** [comment]
Hi

Thanks but I've tried and the instructions are not complete as I can't seem to get the components together as described and I'm not familiar enough to fill in the gaps.

Can I get hold of the 4 folders that Norman used to build it on the last version?    If I can at least build the old one it gives me a pointer to what I need for new one?

Regards
Anthony

**Comment by MeFisto94** [comment]
I guess he doesn't have them anymore and the problem is for some reason we have no chance to build it anymore since we're over a threshold. You see this Linker Error happen for some Unity Guys and the only Solution seems "reducing the filesize", which won't work for an entire JDK.

You can use this to checkout everything (I had some compile errors in openJDK Code before)
```
wget https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.7.0-u80-unofficial-macosx-x86_64-image.zip
unzip openjdk-1.7.0-u80-unofficial-macosx-x86_64-image.zip
hg clone http://hg.openjdk.java.net/jdk7u/jdk7u
cd jdk7u
bash get_source.sh
cd jdk/
hg checkout jdk7u80-b32
cd ../hotspot/
hg checkout jdk7u80-b32
cd ../..
git clone git@github.com:readytalk/avian
git clone git@github.com:readytalk/hello-ios 
```
Also make sure to apply this PR https://github.com/ReadyTalk/avian/pull/480 when you have a new OS, 10.9.5 seems to be too old. (You might see missing TCP IP Header Files when it's wrong)

Then there is this (which is where I am stuck myself, but googling the error doesn't lead to a good solution):
```
         [exec] creating build/ios-arm-interpret-openjdk-src/classpath.jar
         [exec] creating build/ios-arm-interpret-openjdk-src/classpath-jar.o
         [exec] linking build/ios-arm-interpret-openjdk-src/avian
         [exec] ld: Unable to insert branch island. No insertion point available. for architecture armv7
         [exec] clang: error: linker command failed with exit code 1 (use -v to see invocation)
         [exec] make[1]: *** [build/ios-arm-interpret-openjdk-src/avian] Error 1
         [exec] make: *** [build/ios-arm-bootimage-openjdk-src/bootimage-generator] Error 2
```

Good Luck Anyway!

**Comment by MeFisto94** [comment]
The latest sdk Release comes with a bundled avian again. 
Everything should work as expected (apart from a guiNode Bug and that we only Support the 64bit Simulator)
