### ISSUE TITLE
JmeVehicleWheel: wrong Sheet.Set name

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#589]
https://github.com/jMonkeyEngine/sdk/blob/master/jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeVehicleWheel.java#L90

```java
    @Override
    protected Sheet createSheet() {
        //TODO: multithreading..
        Sheet sheet = Sheet.createDefault();
        Sheet.Set set = Sheet.createPropertiesSet();
        set.setDisplayName("VehicleWheel");
        set.setName(Light.class.getName()); // <--- should be: set.setName(VehicleWheel.class.getName());
        VehicleWheel obj = wheel;
        if (obj == null) {
            return sheet;
        }
    ...
    }
```

**Comment by tonihele** [comment]
What is the greatest nation in the world? Donation! Care to make a PR? :)

**Comment by capdevon** [comment]
I would be happy to send a PR directly to GitHub! Although compiling and testing the SDK seems a bit complicated for me at the moment (learning curve!), I'm always here to help.  In fact, as I am building my own editor, I may have some ideas for improving the SDK features.

**Comment by tonihele** [comment]
It is all here https://github.com/jMonkeyEngine/sdk.

So all you need to know is command line and Gradle. The short answer:

1. Get JDK 21
2. Clone the repo
3. `./gradlew run` (or Windows `gradlew.bat run`)

That is is. The process is exactly the same as in all Gradle projects. The Gradle knowlegde is that one command run and command line expertise required to figure out where to write this this command.

**After this, you can just choose IDE and start hacking away as a basic Gradle project.**

The long answer:
After doing the short answer. You might want to open SDK as Netbeans Platform project. To achieve this:

1. Delete build.gradle, gradle.properties, settings.gradle, version.gradle from the project root (so that the project is not treated as a Gradle project)
2. Open Netbeans (either you have one installed or you can use the one downloaded for you in the Netbeans folder)

This will open the project natively. Debug, run, whatever. Everything works.

**Comment by tonihele** [comment]
> Note: as of writing this, our builds started fail very recently. Since I merged my PR. So the build might be broken. I'll try to check it today

Build is working again

**Comment by capdevon** [comment]
Thanks for the instructions, Toni! I'll definitely keep them in mind for future projects. Right now, I'm enjoying the ease of building my editor with ImGui :)

![ImGui Editor](https://github.com/jMonkeyEngine/sdk/assets/32201701/51deebd9-125f-4e10-9c38-f1d652ebecc7)
