### ISSUE TITLE
Animated model causing scene to crash

### ISSUE THREAD

**Issue by jojoofu** [jMonkeyEngine/sdk#69]
here is the model in question.

http://www.katsbits.com/files/md5/animated-md5_bob/bob_lamp_update.zip

This model worked fine in 3.0 but has many issues in 3.1.

The 1st issue I noticed is that the animation controls don't play. The model is divided into parts like head , body , lamp etc. In 3.0 I could play each animation individually. In 3.1 none of the animations play until I get to the last control "lamp_top" then it plays but it also plays all of the other animations at the same time.

I also noted the default master animation control is not loading like it did in 3.0.

The 2nd issue is when I add the model to the scene. After making changes to the model such a moving it I can no longer save my scene then the sdk will start to slow down. If I shut down the scene and reload it most of my models will be absent and I get the error "bone matrixes cannot be null"

If I deleted the model from the scene and reload the scene my other models will reappear.

**Comment by MeFisto94** [comment]
Hey!
Good News:
The second one is already fixed but you'd have to wait for beta2 and since it's hacky we are currently thinking about implementing it differently.

If you need it asap, you have to build the engine from https://github.com/MeFisto94/jmonkeyengine/tree/MatParams (using `gradlew assemble dist`) and then use `mvn install:install-file -U -Dfile=dist/lib/jme3-core.jar -DgroupId=org.jmonkeyengine -DartifactId=jme3-core -Dversion=3.1.0-beta1 -Dpackaging=jar`

This however requires you to have a running linuxoid system with maven available (you actually setup a local maven repo) and placing `mavenLocal() {}` inside the repositories in our gradle.build of the sdk.
Then you can compile your own patched sdk using `./gradlew buildSdk`.

For the first Issue: I also have that problem currently and try to fix it as well, however I can't recall having a default master animation control at all. Anyway we are already on it and trying our best :)

**Comment by jojoofu** [comment]
I should say default blender control. When you load the model in 3.0 you get an empty shell control attached to the root of spatial. It's the default blender control and isn't always empty depending on who set up the animation. To be franks it's not a big issues but the controls not playing is.

I'm in the process of porting a huge project over to 3.1 hopefully by time I'm done we'll have found every possibe bug in the SDK :>

**Comment by Ali-RS** [comment]
Regarding to 1st issue:
Tested your model using xbuf blender exporter and it plays OK in sdk. I do not know why that problem occurs just when using blender importer. :confused: 
![bob_lamp](https://cloud.githubusercontent.com/assets/5787647/15421616/2f454486-1e29-11e6-8eb4-d617a9be3d40.png)

**Comment by MeFisto94** [comment]
Because XBuf Importer only adds one AnimControl and not one per Geometry

**Comment by Ali-RS** [comment]
Strange !! :confused: 
but it plays OK when I import it using ogre exporter and convert it to .j3o
![ogre_animcontrol](https://cloud.githubusercontent.com/assets/5787647/15425167/6dc7a944-1e3b-11e6-8860-0c203114e4eb.png)

**Comment by MeFisto94** [comment]
Did you make sure to only start it on one mesh?
If so, could you please upload the ogre j3o and the blender j3o?
I tried it on my model but there I can't even use the ogre importer :(

**Comment by Ali-RS** [comment]
Yep, I am sure.
here you can download it : https://drive.google.com/open?id=0B35eWZpi0dBoNktmcE5FNTR4ckU

**Comment by MeFisto94** [comment]
So @Ali-RS this was only an issue with the blender importer, right?

**Comment by Ali-RS** [comment]
IIRC yes, it was an issue with blender importer and other importers appear to work fine.

**Comment by MeFisto94** [comment]
Closing as we have gltf now and in case it happens there as well, we can create a new issue.
Also it's most likely something for the engine anyway AND we have the new Animation System anyway.
