### ISSUE TITLE
JME3-AI: Make 3.1 Compatible

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#71]
Hey,
As you all know, our plugins are not really updated but you can use the 3.0 versions (especially the jme3-ai which essentially only provides .jar's).

Now I just found a crash which is related to a small code change:

```
java.lang.NoSuchMethodError: com.jme3.math.Vector2f.interpolate(Lcom/jme3/math/Vector2f;Lcom/jme3/math/Vector2f;F)Lcom/jme3/math/Vector2f;
	at com.jme3.ai.navmesh.NavMeshPathfinder.buildNavigationPath(NavMeshPathfinder.java:308)
	at com.jme3.ai.navmesh.NavMeshPathfinder.computePath(NavMeshPathfinder.java:126)
	at com.jme3.ai.navmesh.NavMeshPathfinder.computePath(NavMeshPathfinder.java:102)
```
It's simply called interpolateLocal in the meantime (TODO: Check if a simple refactoring is enough or if we additonally need a .clone())

The Problem with this (and all plugins is), that we need to wait until updates.jmonkeyengine.org is up again to distribute them and actively use them.

**Comment by grizeldi** [comment]
Will jmonkeyengine.org even be up? I mean are there even plans to fix it?

**Comment by MeFisto94** [comment]
Lol, well I hope so. But honestly it's like this:
If we wanted to set it up, we could basically do that in a matter of a few days (we at least have control over the domain).

But the question is rather how to prevent us from such things happening again. How to decentralyze it a bit and there's the discussion going.

**Comment by grizeldi** [comment]
Ok, right. Maybe giving login credentials to ALL core devs would help? I mean pspeed and nehon are always around (unlike erlend_sh who was citing nehon "abducted by aliens").

**Comment by pspeed42** [comment]
If I took over every job that I thought was being insufficiently done then
I wouldn't even have time to eat or sleep.  The reason I don't have
passwords is because I'd rather pull out all of my own teeth than to debug
web issues.  I wouldn't know where to start to fix this issue and I can
think of about 50,000 other things I'd rather do.  (To include things like
'acquire an infectious disease in a third world country'.)

It's way way way easier for me to just criticize and complain.  :)

**Comment by grizeldi** [comment]
I feel you ;)

**Comment by grizeldi** [comment]
@MeFisto94 is this done by your plugin update?

**Comment by MeFisto94** [comment]
Yes and no. The AI Plugin is available again, but:
a) It's not yet in the official repo
b) We don't know yet where to host it and
c) It only works for some plugins (which rely on the engine itself rather than the sdk)

**Comment by StevenGann** [comment]
So here we are in October and this is still unresolved.

Any way you could "set it up... in a matter of a few days" at least as a temporary measure? I'm all for future-proofing and strategy, but sometimes a temporary fix is valuable too.

**Comment by grizeldi** [comment]
Could we maybe use Github pages for this? I mean we just need a web hist for a couple files, right?

**Comment by MeFisto94** [comment]
Well as a workaround you can use this:
https://github.com/MeFisto94/jme3-artificial-intelligence it also has a ready made nbm under it's releases.

@grizeldi I don't think so because netbeans might need a clean directory listing for that. It seems possible with bintray, though.

The key thing is someone has to take his time to implement some bintray uploading via travis and then there is the fun fact that travis likes to run out of disk space so we need to optimize the build process in a way I can't yet think of.

**Comment by StevenGann** [comment]
@grizeldi I don't see why not. Making it purely decentralized would be almost impossible, but someplace on Github you could host a list of current mirrors. Keep the list as large as possible, with as many mirrors as you can get (free/cheap hosts, volunteers, academic hosts, etc.). Then have JMonkeySDK download that list and start checking the different mirrors until it finds one that is still online and has the desired version.

You could even host that list in several places, and build a static list into each version. If the official list becomes unavailable, it checks the other locations and eventually defaults to the internal list. That's about as decentralized as physically possible, when it comes to web hosting.

What exactly does it need to download? This seems to be the root problem with my attempts to get started with JMonkeySDK, since the entirety of the actual JMonkey engine is absent from the install on every system and OS I've installed it on, with a bunch of dependency errors on build. Is there a reason why it's not in the installer itself, or at least hosted on Github as a download? I know we can manually build it ourselves, but I'm still transitioning from C# to Java, so juggling gradle, build scripts, config files, and three different subversion systems (what's with that?) just to try out an engine is a bit off-putting. JMonkey sounds like a better fit for my needs than Mono, Unity, or Unreal, but this difficulty has really put me off the whole thing.

**Comment by grizeldi** [comment]
Pretty sure sdk has everything you need to start. Just install and it should work. I mean that way works for me and probably also a lot of other people around here.
Just go into the releases sectionnof this repo and download latest one, then install.

Regarding VCSs we are only using git afaik (although some core devs prefer svn, but that's none of my bussines).

**Comment by StevenGann** [comment]
>Pretty sure sdk has everything you need to start. Just install and it should work. I mean that way works for me and probably also a lot of other people around here.

Your workstation probably already has the needed libraries installed, or some other magic I'm missing. A lot of other people have the same issue, based on Google searches. 

`Could not resolve all dependencies for configuration ':core:compile'.`
`> Could not find com.jme3:jme3-core:3.0.10.`
`> Could not find com.jme3:jme3-effects:3.0.10.`
`> Could not find com.jme3:jme3-networking:3.0.10.`
`> Could not find com.jme3:jme3-blender:3.0.10.`
`> Could not find com.jme3:jme3-jbullet:3.0.10.`
`> Could not find com.jme3:jme3-lwjgl:3.0.10.`
`> Could not find com.jme3:jme3-niftygui:3.0.10.`

It searches for each of these packages (which together seem to be the entirety of the engine) in two local directories and 10 web servers, and can't find any of them anywhere. Apparently the engine isn't installed by the SDK installer, and all 10 web hosts return a 404 error. I could build the whole engine from source manually, but the automated script is Linux-only and frankly I was looking into JMonkey in search of a more efficient workflow than Monogame. Monogame has a working installer, and hosts backup binaries on Github just in case.

You should consider hosting the engine on Github too, since it seems to have outlasted all 10 of your other hosts. Or maybe just bundle it directly into the SDK installer, since there's no problems downloading that.

**Comment by StevenGann** [comment]
The point is the @MeFisto94 said they could fix this problem in a couple of days if they wanted to.

Apparently they don't want to, since it's been 5 months and nothing has been done about it.

**Comment by grizeldi** [comment]
Hmm... The engine IS hosted on github in separate repo. @MeFisto94 that sounds like more problems...

@StevenGann Regarding "they could fix it", the only dev working on SDK is @MeFisto94 aka Darkchaos with pull request from other people from time to time. And since he's also working on his own game, you really can't judge that a lot of stuff is still not fixed.

**Comment by StevenGann** [comment]
@grizeldi Fair enough. From the website and other materials I thought JMonkey was professionally maintained. 

Regardless, after a couple days of messing with the installer that doesn't contain the engine and the 10 online hosts that are all offline, I've decided JMonkey is unsuitable for my needs. I'll check back when you guys find a way to bundle the engine into the installer, or when I have enough free time to figure out compiling the engine from the repo myself. If I get around to building it, I'll put a release here on Github for other people hoping to get started quickly.

That's what the Releases section of a repository is for.

**Comment by MeFisto94** [comment]
So first to fix the problem:

> Your workstation probably already has the needed libraries installed, or some other magic I'm missing. A lot of other people have the same issue, based on Google searches.
> 
> Could not resolve all dependencies for configuration ':core:compile'.
> > Could not find com.jme3:jme3-core:3.0.10.
> > Could not find com.jme3:jme3-effects:3.0.10.
> > Could not find com.jme3:jme3-networking:3.0.10.
> > Could not find com.jme3:jme3-blender:3.0.10.
> > Could not find com.jme3:jme3-jbullet:3.0.10.
> > Could not find com.jme3:jme3-lwjgl:3.0.10.
> > Could not find com.jme3:jme3-niftygui:3.0.10.

You might have a misunderstanding about the SDK and the Installer there. What you currently do is a gradle build of the 3.0 engine version. That is (so far) unrelated to the SDK.

To get started you should just click "New -> Project -> Basic Game". When you simply click on the run button the sdk should use the supplied libraries and build your game with it's internal ant build system.

> It searches for each of these packages (which together seem to be the entirety of the engine) in two local directories and 10 web servers, and can't find any of them anywhere. Apparently the engine isn't installed by the SDK installer, and all 10 web hosts return a 404 error. I could build the whole engine from source manually, but the automated script is Linux-only and frankly I was looking into JMonkey in search of a more efficient workflow than Monogame. Monogame has a working installer, and hosts backup binaries on Github just in case.

First: The Engine build itself is not linux only, there is the gradlew.bat. It's as easy as `gradlew.bat assemble` or maybe `gradlew.bat install` so your gradle build can find them locally stored in C:\Users\<...>\.m2\..., but that's another thing.

The problem here also is that you use `3.0` as version instead of `[3.1, )` . The same problem here: We had the 3.0 artifacts on our old self-hosted repo which went down, so it could well be that 3.0 isn't available.

And jme hosts backup binaries on Github just in case (https://github.com/jMonkeyEngine/jmonkeyengine/releases)

> You should consider hosting the engine on Github too, since it seems to have outlasted all 10 of your other hosts. Or maybe just bundle it directly into the SDK installer, since there's no problems downloading that.
https://github.com/jMonkeyEngine/jmonkeyengine/releases
It's just a different repo but actually since it is in the SDK (check your `jmonkeyplatform\libs` folder or click "add library" on your project and they should be there)

> EDIT: Tried uninstalling and reinstalling the SDK. Still no engine. Just an IDE that doesn't recognize existing JMonkey projects and can't compile the default projects, let alone do anything useful.
Can't actually understand that, especially because it should recognize existing projects (which were created by the sdk itself) with ease.

There are actually even [YouTube Tutorials](https://www.youtube.com/watch?v=M1_0pbeyJzI) (Not only this, but from different persons with real voice aswell)

**Comment by StevenGann** [comment]
>You might have a misunderstanding about the SDK and the Installer there. 

You should fix the documentation, then.

From the readme: http://wiki.jmonkeyengine.org/doku.php/sdk:development

Hey look, yet another 404! Let's try again.

https://jmonkeyengine.github.io/wiki/

>You want to… Get started with jMonkeyEngine

>Then download... 	jMonkeyEngine SDK

>You receive… SDK, binaries, javadoc, sources

The problem is that I receive none of the. Just an IDE, which you call an SDK. No engine. I'm the first to tell people to RTFM, but when TFM is wrong, you can't fault the user. I only know what your sparse, vague documentation tells me.

>To get started you should just click "New -> Project -> Basic Game". When you simply click on the run button the sdk should use the supplied libraries and build your game with it's internal ant build system.

Nope. Unresolved dependencies. Compiling with gradle directly (following the OpenRTS instructions) gives exactly the same errors.

>First: The Engine build itself is not linux only, there is the gradlew.bat. It's as easy as gradlew.bat assemble or maybe gradlew.bat install so your gradle build can find them locally stored in C:\Users<...>.m2..., but that's another thing.

Doesn't work for me. Tried it, tried it as Administrator, tried it on Win10 and Win7 on 3 different computers. It does a whole lot of something, but nothing happens. Perhaps because there is no "C:\Users\...\.m2" directory? Am I supposed to create that? The documentation says to just run the SDK installer. Besides, why in the world would anything go in Users? This is precisely what Program Files is for. I know this is common practice with Java, but it's still bad practice with Windows.

Even then, what's the point of distributing an installer if the software has to be manually compiled anyway?

> so it could well be that 3.0 isn't available.

Well that's a problem because the engine I'm trying to get running requires 3.0.10. Doesn't it defeat the purpose of version control if you're still this vulnerable to server losses? You don't have copies of 3.0.10 _anywhere else?_ Consider getting a USB drive for important files like that. Or try a service like OneDrive, Google Drive, or Dropbox. It's really convenient and you won't have to worry about losing the only copies of your files when all 10 websites go down at once.

>And jme hosts backup binaries on Github just in case 

...of betas, alphas, and snapshots. I take it you never used Github for releases prior to 3.1?

>There are actually even YouTube Tutorials

I am following [this tutorial.](https://github.com/methusalah/OpenRTS) Unfortunately the SDK installer, even the SDK 3.0.10 installer, never actually installs the engine so I'm just out of luck.

Like I said, apparently JMonkey just isn't suitable for my needs. I thought it was professionally maintained, and even then I thought it was maintained by people who would have enough sense to provide downloads of a stable version instead of requiring everyone to migrate to a new beta.

Again, I'll be sticking with Monogame. It's professionally maintained, has a working installer, and old versions are readily available without having to recompile everything yourself. I just don't like the low-level API and the external asset pipeline, which JMonkey seems to do a better job of (The SDK/IDE looks amazing!), and I don't like how restrictive and clunky Unity is, so JMonkey's architecture looks like a happy medium. Unfortunately I can't install or compile anything with JMonkey, let alone OpenRTS which I wanted to base my project off of, so that's sort of a dealbreaker.

**Comment by grizeldi** [comment]
The "unstable" beta is more stable than the latest "stable" 3.0 build.
Basically 3.1 is stable but core team doesn't want to name it stable
because dunno, "personal reasons" or what should I call it (pspeed please
don't start it again here). There have been quite some debates on the forum
in that regard but it's still called beta. You should seriously consider
3.1 since 3.0 is quite buggy in some aspects.
Also github was used even before, but releases were made in the engine
repository itself (not this one).

27. okt. 2016 18.08 je oseba "Steven Gann" <notifications@github.com>
napisala:

You might have a misunderstanding about the SDK and the Installer there.

You should fix the documentation, then.

From the readme: http://wiki.jmonkeyengine.org/doku.php/sdk:development

Hey look, yet another 404! Let's try again.

https://jmonkeyengine.github.io/wiki/

You want to… Get started with jMonkeyEngine

Then download... jMonkeyEngine SDK

You receive… SDK, binaries, javadoc, sources

The problem is that I receive none of the. Just an IDE, which you call an
SDK. No engine. I'm the first to tell people to RTFM, but when TFM is
wrong, you can't fault the user. I only know what your sparse, vague
documentation tells me.

To get started you should just click "New -> Project -> Basic Game". When
you simply click on the run button the sdk should use the supplied
libraries and build your game with it's internal ant build system.

Nope. Unresolved dependencies. Compiling with gradle directly (following
the OpenRTS instructions) gives exactly the same errors.

First: The Engine build itself is not linux only, there is the gradlew.bat.
It's as easy as gradlew.bat assemble or maybe gradlew.bat install so your
gradle build can find them locally stored in C:\Users<...>.m2..., but
that's another thing.

Doesn't work for me. Tried it, tried it as Administrator, tried it on Win10
and Win7 on 3 different computers. It does a whole lot of something, but
nothing happens. Perhaps because there is no "C:\Users....m2" directory? Am
I supposed to create that? The documentation says to just run the SDK
installer. Besides, why in the world would anything go in Users? This is
precisely what Program Files is for. I know this is common practice with
Java, but it's still bad practice with Windows.

Even then, what's the point of distributing an installer if the software
has to be manually compiled anyway?

so it could well be that 3.0 isn't available.

Well that's a problem because the engine I'm trying to get running requires
3.0.10. Doesn't it defeat the purpose of version control if you're still
this vulnerable to server losses? You don't have copies of 3.0.10 *anywhere
else?* Consider getting a USB drive for important files like that. Or try a
service like OneDrive, Google Drive, or Dropbox. It's really convenient and
you won't have to worry about losing the only copies of your files when all
10 websites go down at once.

And jme hosts backup binaries on Github just in case

...of betas, alphas, and snapshots. I take it you never used Github for
releases prior to 3.1?

There are actually even YouTube Tutorials

I am following this tutorial. <https://github.com/methusalah/OpenRTS>
Unfortunately the SDK installer, even the SDK 3.0.10 installer, never
actually installs the engine so I'm just out of luck.

Like I said, apparently JMonkey just isn't suitable for my needs. I thought
it was professionally maintained, and even then I thought it was maintained
by people who would have enough sense to provide downloads of a stable
version instead of requiring everyone to migrate to a new beta.

Again, I'll be sticking with Monogame. It's professionally maintained, has
a working installer, and old versions are readily available without having
to recompile everything yourself. I just don't like the low-level API and
the external asset pipeline, which JMonkey seems to do a better job of (The
SDK/IDE looks amazing!), and I don't like how restrictive and clunky Unity
is, so JMonkey's architecture looks like a happy medium. Unfortunately I
can't install or compile anything with JMonkey, let alone OpenRTS which I
wanted to base my project off of, so that's sort of a dealbreaker.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jMonkeyEngine/sdk/issues/71#issuecomment-256691390>,
or mute
the thread

**Comment by normen** [comment]
Stable means we won't make changes to the API, unstable means changes to the API can still happen. The SDK specifically points you to the INCLUDED documentation when you start it up, just press F1.

As for the web situation, its seriously messed up but nobody denies that. "Professional" would imply that somehow somebody is paid so in that respect NO, we're not professional, nobody gets money for doing what we do. Which is also why we won't point fingers at those who basically caused the web situation.

Having said that, none of you guys paid any money for being able to use the engine or SDK either so if you're incapable of making use of the offerings (which SO MANY people are able to) then please complain to yourself.

Closing this issue as the base issue of finding a place for the SDK plugins is known and will be dealt with if/when possible.

**Comment by Pesegato** [comment]
Maybe this one solves all of @StevenGann issues?

https://github.com/jMonkeyEngine/sdk/releases/tag/stable

**Comment by StevenGann** [comment]
@Pesegato Tried that one. Still no engine installed.

>The binaries contains the sdk and the engine.

If they do, they don't install anywhere I can find.

**Comment by pspeed42** [comment]
When you create a JME Game project, it will depend on the libraries and they will be there.  You should be able to create a new JME Game project, hit "run", and see the blue cube.
