### ISSUE TITLE
Comparing changes addition highlight is hardly readable

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/sdk#75]
Comparing changes addition highlight is hardly readable. Is it just me or is the pale green making it hard to read the texts?
![compare](https://cloud.githubusercontent.com/assets/8344766/15985034/e7c2df48-2fe8-11e6-88b7-b95caf5dea27.png)

**Comment by MeFisto94** [comment]
I found this:
https://github.com/Revivius/nb-darcula/blob/03e12b7d38068f19f95ee84cd0ea1e4344bccbf5/src/main/java/com/revivius/nb/darcula/DarculaLFCustoms.java#L437

It also contains the "fix" for the other problem you found and it seems that the debugger needs a complete overhaul as well.
I'm currently quite busy but I try my best in fixing it (Actually you'd have to build from git since we can't release currently, anyway)

**Comment by tonihele** [comment]
The normal text selection highlight is also not so visible. It is light gray against dark gray. A bit demanding to make these themes. To find the right combination of colors.

**Comment by MeFisto94** [comment]
For some reason the fix I did didn't get applied, I need to investigate a bit more :/

**Comment by MeFisto94** [comment]
Hey, it should now definately work as expected.
I simply took the Colors of Darcula but you can change them under Preferences -> Fonts & Colors -> Diff.
Unfortunately, this does not solve #74 because for some reason it uses the defined value for gitignored files, but seems to completely ignore/overwrite the color for changed files.

**Comment by MeFisto94** [comment]
To comment on the latest fix (e5a25fe): We still have that odd behavior of the LFCustoms not being applied most of the time, I only had it happen a few random times and I don't know why.

However I found out that our Fonts & Colors (FaC) were overriding the values of the LFCustoms anyway, so I changed them. Unfortunately there only seems to be values for `diff` and not for `git` so far or at least I did not find a good documentation on those colornames other than:

https://github.com/Revivius/nb-darcula/blob/master/src/main/resources/com/revivius/nb/darcula/Editors/text/x-diff/FontsColors/Darcula/tokenColorings.xml
and
https://github.com/fentie/netbeans-colors-solarized/blob/master/config/Editors/text/x-diff/FontsColors/Netbeans_Solarized_Dark/org-netbeans-modules-editor-settings-CustomFontsColors-tokenColorings.xml
