### ISSUE TITLE
Windows x64 installer broken

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#79]
I just downloaded the win x64 installer and tried to update my sdk to the newest relase.
First the netbeans "configuring installer" pops up and completes successfully. However on the next window it says "click next to continue". I click next and the process just quits. Tried it several times and it never worked.
Maybe it would help to uninstall current installation, but since it seems the new installer is broken, I'm not really sure, I want to do that.

**Comment by MeFisto94** [comment]
See [docs/reporting_issues.md](https://github.com/jMonkeyEngine/sdk/blob/master/docs/reporting_issues.md#reporting-faults-in-the-netbeans-installer) 
If it says something like can't build component in wizard.xml or such, it's definetely save to delete.

We have that problem that the installer can't actually update an existing installation, but since I don't know enough about the installer to fix that, you have to uninstall your other version first.

Note: You could also set up a Virtual Machine (VM) to try if the installer works there.

**Comment by grizeldi** [comment]
Whoops, sorry, never saw that reporting issues thing. I tried running it in command line before, but it returns the moment I hit enter.
Now I managed to grab the log:
http://pastebin.com/j3bXNqWm

**Comment by MeFisto94** [comment]
Yeah, that's really strange... Maybe you were to impatient?
Did you also try --verbose? 

From what we currently see it's hard to tell :/

**Comment by grizeldi** [comment]
Yes, that log is with the --verbose flag.

**Comment by MeFisto94** [comment]
Mh it's hard to tell what's going wrong in this case. Do you have another computer or something where you can try it? Maybe it really fails because of the old sdk version still existing?
And you verified that there is no process running (Like if the installer would restart itself) and you had enough space in Temp? (On Harddrive C)

**Comment by grizeldi** [comment]
No, that's sadly only win7 pc I have available... The process simply exits, I checked it in task manager. The prpcess was there and then when the window closes, the process exits as well. C: disk had about 200GB left, so that shouldn't be the issue.

**Comment by MeFisto94** [comment]
Strange. Well I meant you could use some Virtual Machine Software, I think Oracle's Virtualbox is Freeware and there might even be one from Microsoft.

You could also try the latest release but I doubt it changes something. It's actually problematic to debug from thereon.

You could look into C:\Users\grizeldi\AppData\Roaming\ there could be some `jmonkeyplatform-installer` folder. Either it has additional logs or you can try what happens when you delete it.
Don't delete a simple `jmonkeyplatform` though as it will lead to loss of your settings and such.

**Comment by grizeldi** [comment]
No, in my appdata there is sadly no jmonkeyplatform-installer folder. There
is only .jmonkeyplatform...

**Comment by MeFisto94** [comment]
I also just saw: Try `C:\Users\grizeldi`, you might need to turn on "Show invisible Folders" though

**Comment by grizeldi** [comment]
Also installer for the same version, just Linux x86 works great on the exactly same machine, just another OS booted.

**Comment by grizeldi** [comment]
Deleting the C:\Users\grizeldi.jmonkeyplatform-installer folder did the job and installer now runs, but is that how it's supposed to be?

**Comment by MeFisto94** [comment]
Yeah, it's strange. And actually close to impossible to debug it from that case.
Did you delete that jmonkeyplatform-installer, since it contains something installer related?

I hope it's not trying to access our homepage which is down, but yeah, that's definately hard to debug without. 

Edit: Seeing your comment: Glad it worked! No it's not supposed to be like this but we have no clue on what is crashing the installer there and since we can't actually execute some code in the early phase of the installer, there isn't much we can do about that.

The Background seems to be this, though: The Folder shows that the SDK is installed and then maybe it looks in some folder or want's to do some Upgrade or w/e.
But Hey, it works! So i'm closing this as it's actually comparable to #57, something is simply wrong here :(
