### ISSUE TITLE
Can not find class XbufLoader

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/sdk#81]
Hi
Using latest release of SDK (with Xbuf). 
I added "jme3_xbuf" library in SDK to my project.
Now trying to register XbufLoader in :`assetManager.registerLoader(XbufLoader.class, "xbuf");` 
but it can not find XbufLoader class.
Seems it just imported this library : https://github.com/xbuf/xbuf but NOT this : https://github.com/xbuf/jme3_xbuf .

**Comment by MeFisto94** [comment]
Well the Goal was to have XBuf Integration in the SDK, not User Code. Did it add the jme3_xbuf library to your SDK Libraries? If yes then this wasn't intentional and is because the sdk needs them to be built. 

It should, however, provide the XbufLoader class then. Have you looked at which jars are present in that jme3_xbuf?

**Comment by Ali-RS** [comment]
Take a look : 
![untitled](https://cloud.githubusercontent.com/assets/5787647/16540638/95c23a16-4020-11e6-8857-3dafb906c5a8.png)

The jme3_xbuf0.8.4.jar is empty!

**Comment by Ali-RS** [comment]
the latest version of xbuf.jar is 8.2.0
https://github.com/xbuf/xbuf/releases
https://jitpack.io/org/xbuf/xbuf/0.8.2

> Does it work when simply using the 0.8.2 Version?
we need to also have jme3_xbuf_loader.jar  to be able to load .xbuf and it is in a different repo : 
https://github.com/xbuf/jme3_xbuf/tree/master/jme3_xbuf_loader

Anyway trying directly convert .xbuf to .j3o in SDK by right clicking on .xbuf and converting to .j3o works OK.

**Comment by MeFisto94** [comment]
This issue is actually still valid, it is just that I don't understand the packaging process much as well as the fact that it's automated somehow, but we need to find a solution.

In Regards to Contribution Welcome: In the build.gradle there is code to generate some netbeans subproject xmls (jme3-libraries) which just generates a module which contains the jars.
