### ISSUE TITLE
SDK freezing on importing a blender model

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#82]
I'm trying to import a model generated using the procedural spaceship generator (discussion here: https://hub.jmonkeyengine.org/t/procedural-spaceship-generator-in-blender/36198).
Convert to j3o and view model produce basically the same freeze. The loading procedure seems normal until it tries to load the normal map and pops up a warning "The texture coordinates type is not supported: TEXCO_GLOB. The texture 'Normal Map'". That's the last thing that happens and then even "sudo kill [processID]" doesn't kill it immediately. After restarting the SDK the j3o is there but without textures.
Now the problem lies here: the texture coordinates once really were global, but I changed them to UV (well, I tried pretty much everything). SDK still says that they are global. What's going on? Is SDK using some old copy or might the spaceship generator keep overriding my fixes?

**Comment by grizeldi** [comment]
Regarding old texture mappings:
I changed them in one material but not the other :facepunch: 
However I think that SDK shouldn't freeze for that.
Also OS details: Ubuntu 15.10 32 bit

**Comment by grizeldi** [comment]
I was using version 3.1-beta1-SNAPSHOT (github relase). Triangulate modifier was applied, but SDK still didn't like it...
Later it started to complain about Java heap memory error...

**Comment by MeFisto94** [comment]
[docs/reporting_issues.md](https://github.com/jMonkeyEngine/sdk/blob/master/docs/reporting_issues.md) states that you should supply your model :stuck_out_tongue: 

Also try the xbuf release since that triangulation/log spam fix occured after beta1, maybe it's still the same issue but spamming when it doesn't like blenders triangulation or something.

As for heap, you have to look into the wiki: [SDK: Increasing Heap Memory](https://jmonkeyengine.github.io/wiki/sdk/increasing_heap_memory.html), this happens mostly when your Textures are simply big

**Comment by MeFisto94** [comment]
I'm closing this for now because of inactivity. If this issue is reproducable on any model feel free to post it here. 

As a next step it would be good to see what happens when loading the same model as a regular jme project, to see if it is only sdk related or maybe some endless loop inside of the blender/xbuf importer.
