### ISSUE TITLE
maven updatesite broken

### ISSUE THREAD

**Issue by spirritus** [jMonkeyEngine/sdk#84]
Hi there,
http://updates.jmonkeyengine.org/maven/ leads into nirvana ...
PLZ  fix this for all the happy maven users :-)

Cheers

**Comment by MeFisto94** [comment]
This is actually not related to the SDK but rather to the Engine itself `jMonkeyEngine\jmonkeyengine`.
Yes we know about this, actually our whole webpresence is broken.
You can use our bintray though or do what the SDK does: [build_engine.sh](https://github.com/jMonkeyEngine/sdk/blob/master/build_engine.sh)

Btw: The bintray is missing jme-test-data jme3-jbullet and something else I can't remember. That's why we have build_engine.sh
