### ISSUE TITLE
Focus jumps to 'Libraries' when I create a new scene in JME 3.1 beta 

### ISSUE THREAD

**Issue by nordfalk** [jMonkeyEngine/sdk#98]
When I create a new scene in JME 3.1 beta or beta1-b002-SNAPSHOT
![image](https://cloud.githubusercontent.com/assets/1143272/18704061/b9feb9e2-7fe8-11e6-8f5f-29cb5bb7cb70.png)

the focus jumps down to 'Libraries' 
![image](https://cloud.githubusercontent.com/assets/1143272/18703983/72cea406-7fe8-11e6-9713-b47ed3c16e8b.png)

and the new screne isnt opened.

I have to scroll up again to Project Assets and open it manually.

(do you want UI bug reports such as these? The make it hard for newcomers but you might not want to polish these parts yet)

**Comment by nordfalk** [comment]
I see this is a duplicate of https://github.com/jMonkeyEngine/sdk/issues/62

**Comment by MeFisto94** [comment]
Yes we do want such kind of reports but we have no clue how to fix it actually.
It used to work at 3.0 but there were no changes related to that. It seems to be some Race Condition since the assets are actually a part of the library.

Also the assets are opened but the library opens last.

**Comment by nordfalk** [comment]
I'd be willing to bisect this error - to find the commit where this problem started to appear.
Problems is: Should I clone and build https://github.com/jMonkeyEngine/sdk, or https://github.com/jMonkeyEngine/jmonkeyengine ?
I'm confused as the 2 repos seems to have a lot of directories in common

**Comment by Ali-RS** [comment]
JME SDK is separated from engine since while. 
You should build from  https://github.com/jMonkeyEngine/sdk which also will build engine.
https://github.com/jMonkeyEngine/jmonkeyengine contains engine source.

**Comment by grizeldi** [comment]
If I had to guess, I'd say it started to appear when @MeFisto94 updated underlying netbeans platform.
Try checkung that.

**Comment by nordfalk** [comment]
OK, I understand now: jmonkeyengine is 'the library' with the core classes and SDK is the 'whole bunch' and using the engine.

The problem also exists in 3.1-alpha2-FINAL (https://github.com/jMonkeyEngine/sdk/releases/tag/3.1-alpha2), which is the earliest 3.1 release I can get hold of.

So, @grizeldi you are probably right. 

I don't know where to go from here...

**Comment by grizeldi** [comment]
Continues in the engine repo, since sdk was once part of the engine repo, but got separated.
Alpha 1 release https://github.com/jMonkeyEngine/jmonkeyengine/releases/tag/v3.1-alpha1

**Comment by MeFisto94** [comment]
It's pretty simple:
Before 3.1-alpha2 the SDK was part of the main project but in the "sdk" folder.
The bad thing is that due to the move from google code we don't have ALL commits. So the last one is from normen "Moving to gradle layout". 

Somewhere between this and 3.1-alpha1 the Error must have been introduced.

**Comment by nordfalk** [comment]
I can confirm that the problem also exists in the v3.1-alpha1 release.

**Comment by nordfalk** [comment]
@MeFisto94 , so in the SDK this commit

commit 15f5424ae8e6f23d06b394f36a6839df3c255873
Author: Normen Hansen <normen667@gmail.com>
Date:   Sun Mar 23 12:31:26 2014 +0100

    - include SDK in gradle build
    - add option to build natives / SDK to gradle properties
    - update SDK properties file with jme version


and in the engine this commit

commit d4546223fc226e2e258b96932cb01ebbca85b107
Author: Normen Hansen <normen667@gmail.com>
Date:   Sun Mar 23 12:31:26 2014 +0100

    - include SDK in gradle build
    - add option to build natives / SDK to gradle properties
    - update SDK properties file with jme version


I dont know much about how to checkout and build it all from that point.
I guess http://davidb.github.io/sandbox_wiki_jme/sdk/build_platform.html#building-jmonkeyengine-sdk-yourself can help me, and Ill give it a try sometime next week

**Comment by MeFisto94** [comment]
Older than 3.1-alpha1 always take the jmonkeyengine repo (since the SDK is only some git magic and might miss something).

Building the SDK was something like `./gradlew buildSdk` and then either using netbeans to create the zips or (on linux) use ant for something like "zipDistribution" or (way easier) ant run.
The latter inside the sdk folder

**Comment by nordfalk** [comment]
Thanks, but the gradle builds around march 2014 can't be executed anymore as Google Code has been shut down.

Execution failed for task ':jme3-bullet-native:downloadBullet'.
> Can't get http://bullet.googlecode.com/files/bullet-2.82-r2704.zip to /home/j/3D-briller/jme_github/jmonkeyengine/jme3-bullet-native/bullet.zip

There's no ./gradlew buildSdk task there so this is just issuing './gradlew build'

**Comment by normen** [comment]
@MeFisto94 

> It's pretty simple:
> Before 3.1-alpha2 the SDK was part of the main project but in the "sdk" folder.
> The bad thing is that due to the move from google code we don't have ALL commits. So the last one is from normen "Moving to gradle layout".
> 
> Somewhere between this and 3.1-alpha1 the Error must have been introduced.

It started when the NetBeans base was updated so its not really our code. And all the svn commit history is included in git, its just that the GitHub UI doesn't show it.

**Comment by grizeldi** [comment]
Well if it's netbeans' fault is there any newevr version than the one we are currently using? If it is, would updating to it help?

**Comment by MeFisto94** [comment]
@nordfalk  I have no clue what exactly you are doing, but see the master build file: https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/gradle.properties#L22
I suspect that you do things wrong though, since it shouldn't rebuild the native libraries each time.

As for 3.0: https://github.com/jMonkeyEngine/jmonkeyengine/blob/3.0/sdk/build.xml -> This is the oldest version, ant build might work there, but it doesn't automatically download the Netbeans like the new gradle scripts do.

As for 3.1-alpha1 (which is the latest version with the old (8.0) netbeans version), go here: https://github.com/jMonkeyEngine/jmonkeyengine/tree/v3.1-alpha1/sdk and then in _this_ directory, execute ./gradlew buildSdk (You executed build in the main repo, not sdk).

You might encounter problems due to the engine not being completely on bintray, you might fix this by simply leaving out the engine dependencies, or take a look at the latest build_engine in the sdk project on master and adjust the engine version to 3.1.0-master-SNAPSHOT then, or whatever it will be installed as.

BTW: Since #62 is part of #7 or jMonkeyEngine/#329 (4.09.2015, 3.1-alpha1 was released 18.08.2015), it is completely unrelated to the new Netbeans base, since this was introduced around this march.

As such, I suspect the issue being there since at least 3.1-alpha1

**Comment by nordfalk** [comment]
Hi @MeFisto94 

As you can see from https://github.com/jMonkeyEngine/jmonkeyengine/tree/v3.1-alpha1/sdk there _is_ no  gradlew there, hence I cannot issue ./gradlew buildSdk.

Anyway Ive copied gradlew and the wrapper from the SDK project and managed to delete the bullet dependencies and build the source.
2015-08-02 19:28:13 Tags: 3.1-snapshot-test 3.1-snapshot-test-2 version  - contains the error.

2015-04-03 05:50:37 contains the error.

2015-02-16 14:49:00  contains the error  (and its using netbeans 8.0.2)

2015-01-31 22:18:13  contains the error

2015-01-22 22:36:54  contains the error 

2015-01-22 22:05:39 contains the error 

2015-01-21 21:39:06 contains the error 

2015-01-20 23:43:42 contains the error 

2015-01-20 18:54:49 contains the error 

2015-01-20 10:28:12 contains the error  (project template is broken, but opening an existing project shows the behaviour)

2015-01-14 00:28:39 contains the error (but project template is broken)

2014-12-28 16:23:34  contains the error 

2014-11-18 04:42:41 contains the error (project template is broken, but opening an existing project shows the behaviour)

2014-11-09 18:22:05 contains the error  (project template is broken, but opening an existing project shows the behaviour) 

2014-11-09 17:55:51 and earlier (so before 'Fix SDK build on JDK8' commit) I get a compiler error:

[ant:nb-javac] /home/j/3D-briller/jme_github/jmonkeyengine/sdk/jme3-terrain-editor/src/com/jme3/gde/terraineditor/AddTerrainAction.java:172: error: cannot access LookupProvider
[ant:nb-javac]         TerrainLodControl control = new TerrainLodControl(terrain, SceneApplication.getApplication().getCamera());
[ant:nb-javac]                                                                                    ^
[ant:nb-javac]   class file for org.netbeans.spi.project.LookupProvider not found


All in all the error was also there before 2014-11-09.
I might try with java 7 compiler later on.

Jacob

**Comment by nordfalk** [comment]
Java 7 gave the same error: cannot access LookupProvider

class file for org.netbeans.spi.project.LookupProvider not found - where can I find it?

**Comment by MeFisto94** [comment]
Well, you can use the gradlew from the main folder and run it against the sdk folder I suppose, anyhow the main building work is in the ant files, gradle is only some preparational work.

What happens when you apply said Fix-Commit to older versions of the code? I don't know what the Fix actually does, haven't looked into it.

The Lookup Provider is part of the Netbeans Code and thus might be some build-related error?
Actually you have to build then ant build.xml which should include the whole netbeans thing.

Or, let's say it like this:
You have a `sdk/netbeans/bin/netbeans.exe`, right? Then start it, open the sdk folder there and try to launch the SDK from there. That way we can be certain that we don't have any building problems,

Also note that you have to delete and redownload this netbeans folder each time you switch between 8.0.2 and 8.1 (so after you got back to 8.0, the source might be using an older version of the netbeans api but only 8.1 is provided).
I'm saying this because I remember that there were some package changes from 8.0 to 8.1 which might be the root of this, so Are you really building with nb 8.0 at that point?

**Comment by nordfalk** [comment]
Thanks for the guidance.

Ive managed to go further back in history by switching completely to JDK 7:

2014-11-09 17:55:51 same

2014-11-01 13:27:19 same

2014-06-19 07:35:13 same

2014-03-24 05:47:08 same

So... either Im doing something wrong or the error is really old.

For the 2014-03-24 05:47:08 build Im seeing a 3.0 splash screen and the log states
  Product Version         = jMonkeyEngine SDK 3.1-pre-alpha-svn (#8230772f5f18)

I'll try again next week when I have time.

Jacob

**Comment by nordfalk** [comment]
Finally, Ive found a build where the problem doesent exist!


The problem is not present in commit from 2014-02-17 15:14:32 to 2014-03-20 09:12:44 (I had to build it with Netbeans 7.3)

After this comes commit 2014-01-07 06:44:17 "copying the source files with history into the new gradle-based structure".

So... to me it seems that the problem was not present at 2014-01-07 (Netbeans 7.3), and it somehow started between that date and is present in 2014-03-24 (Netbeans 8.0.2).

Here are the commits that happens in between.

![image](https://cloud.githubusercontent.com/assets/1143272/19310642/6ab35682-908b-11e6-9823-5b6481bb5929.png)
![image](https://cloud.githubusercontent.com/assets/1143272/19310684/9f8912ca-908b-11e6-9e89-7abab2d7ed49.png)

I couldnt compile (neither using Netbeans 7.3 or using the bundled Netbeans 8.0.2) between these points, but at least the error is narrowed down to be somewhere in these 80 commits.

@MeFisto94 or @normen it would be great if you found the time to confirm this.

Jacob

**Comment by grizeldi** [comment]
Wow great job! Hopefully now someone can fix this most annoying current bug?

**Comment by Ali-RS** [comment]
Great
Thanks a lot.

**Comment by nordfalk** [comment]
Just for the record (and Google) I managed to solve the "cannot access LookupProvider
class file for org.netbeans.spi.project.LookupProvider not found" problem.

You need to add "Project API" to the dependencies for the NavMeshGen, Terrain Editor, Vechicle Creator and Scene Composer sub-projects.
![image](https://cloud.githubusercontent.com/assets/1143272/19315527/4fdd099e-909e-11e6-8d94-4bbb9dd354a8.png)

**Comment by MeFisto94** [comment]
Well for that LookupProvider Problem, this should only happen when you build pre-8.1 code with NB 8.1, as this should already be done by some commits to xml files.

As for the other thing: Are you able to compile the last present commit with NB 7.3 instead of NB 8.0 (2014-03-24 aka 9d6eb91).

It seems that NB 8.0 was introduced around e226f6d (2014-03-24), but the commit also states, that at least the gradle build was under construction there, so this could be the reason for the build not working.

Cross fingers everybody, that this is not a netbeans bug

**Comment by MeFisto94** [comment]
I don't know why I reopened this back in the day but due to duplication rules actually #62 would be the proper issue to live on (the first opened). This issue has valueable information though.
